---
- name: deploy mysql
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: mysql
        namespace: "{{ namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: visitors
            tier: mysql
        template:
          metadata:
            labels:
              app: visitors
              tier: mysql
          spec:
            containers:
            - name: visitors-mysql
              image: "mysql:5.7"
              ports:
                - name: mysql
                  containerPort: 3306
                  protocol: TCP
              env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                - name: MYSQL_DATABASE
                  value: visitors
                - name: MYSQL_USER
                  value: visitors
                - name: MYSQL_PASSWORD
                  value: visitors
- name: create mysql service
  k8s:
    definition:
      kind: Service
      metadata:
        name: mysql-service
        namespace: "{{ namespace }}"
        labels:
          app: visitors
          tier: mysql
      spec:
        clusterIP: None
        ports:
          - port: 3306
        selector:
          app: visitors
          tier: mysql
